export const API_REQUEST_START = 'API_REQUEST_START';
export const API_REQUEST_SUCCESS = 'API_REQUEST_SUCCESS';
export const API_REQUEST_ERROR = 'API_REQUEST_ERROR';
export const API_TOKEN_INITIALIZE = 'API_TOKEN_INITIALIZE';
export const API_TOKEN_RESET = 'API_TOKEN_RESET';
