
export const SESSION_CREATE_REQUEST = 'SESSION_CREATE_REQUEST';
export const SESSION_CREATE_SUCCESS = 'SESSION_CREATE_SUCCESS';
export const SESSION_CREATE_FAILURE = 'SESSION_CREATE_FAILURE';

export const SESSION_DESTROY_REQUEST = 'SESSION_DESTROY_REQUEST';
export const SESSION_DESTROY_SUCCESS = 'SESSION_DESTROY_SUCCESS';
export const SESSION_DESTROY_FAILURE = 'SESSION_DESTROY_FAILURE';
